### ISSUE TITLE
Recursion depth exceeded while calling pstree

### ISSUE THREAD

**Issue by RaeldZues** [murchisd/splunk_pstree_app#5]
pstree.py - recursion depth exceeded while calling a python object. Line 85. 
Assumption that this would be limited in a small scale specific search.

**Comment by murchisd** [comment]
Hi @RaeldZues, this is a Splunk limitation. Recursion depth cannot exceed 7. I will look in to converting the app to use iterative method instead of recursion.

**Comment by murchisd** [comment]
Branch [pstree_v2](https://github.com/murchisd/splunk_pstree_app/tree/pstree_v2) created with an iterative method for this app. You can install the tgz file on an instance of Splunk and run the search using `pstree_v2` instead of `pstree`. The recursive method can still be called with `pstree` for comparison.

**Comment by murchisd** [comment]
@RaeldZues let me know if the iterative method of PSTree  mentioned above solves your issue

**Comment by murchisd** [comment]
Pstree 2.0 has been vetted and approved by Splunk for On-Prem and Cloud deployments. By default, it uses an iterative method and should not cause recursion error.
